smart_library/categories/urls.py
from django.urls import path

from smart_library.categories.views import CategoriesView

urlpatterns = [
    path('', CategoriesView.as_view(), name='categories')

]

smart_library/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('smart_library.common.urls')),
    path('accounts/', include('smart_library.accounts.urls')),
    path('authors/', include('smart_library.authors.urls')),
    path('categories/', include('smart_library.categories.urls')),
    path('books/', include('smart_library.books.urls')),
    path('reviews/', include('smart_library.reviews.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smart_library/books/models.py
import datetime
import uuid

from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, MinValueValidator
from django.db import models

from smart_library.accounts.models import AppUser
from smart_library.authors.models import Author
from smart_library.categories.models import Category
from smart_library.core.validators import validate_book_name


class Book(models.Model):
    MIN_LENGTH_BOOK_TITLE = 2
    MIN_VALUE_BOOK_PRICE = 1

    IMAGE_UPLOAD_TO_DIR = 'books/'

    book_title = models.CharField(
        max_length=50,
        unique=True,
        validators=(
            MinLengthValidator(MIN_LENGTH_BOOK_TITLE),
            validate_book_name,
        ),
    )

    book_image = models.ImageField(
        upload_to=IMAGE_UPLOAD_TO_DIR,
        null=False,
        blank=False,
    )

    description = models.TextField(
        null=False,
        blank=False,
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
    )

    author = models.ForeignKey(
        Author,
        on_delete=models.CASCADE,
        related_name='books',
    )

    serial = models.CharField(
        max_length=30,
        unique=True,
        editable=False,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    price = models.FloatField(
        validators=(
            MinValueValidator(MIN_VALUE_BOOK_PRICE),
        ),
    )

    def __str__(self):
        return self.book_title

    def save(self, *args, **kwargs):
        if not self.serial:
            while True:
                serial = uuid.uuid4().hex[:12].upper()
                if not Book.objects.filter(serial=serial).exists():
                    break
            self.serial = serial

        super().save(*args, **kwargs)

    class Meta:
        ordering = ('id', )


class RentBook(models.Model):
    user = models.ForeignKey(
        AppUser,
        on_delete=models.CASCADE,
    )
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    period_start = models.DateField()
    period_end = models.DateField()

    def clean(self):
        current_date = datetime.date.today()
        if self.period_start < current_date:
            raise ValidationError("Period start cannot be a date earlier than today.")
        if self.period_start > self.period_end:
            raise ValidationError("Period start cannot be later than Period end.")
        super().clean()

    def __str__(self):
        return self.user.username

smart_library/categories/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from smart_library.core.validators import validate_only_letters


class Category(models.Model):
    MIN_LENGTH_CATEGORY = 3
    MAX_LENGTH_CATEGORY = 30

    name = models.CharField(
        max_length=MAX_LENGTH_CATEGORY,
        unique=True,
        validators=(
            MinLengthValidator(MIN_LENGTH_CATEGORY),
            validate_only_letters,
        ),
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

smart_library/categories/views.py
from django.shortcuts import render
from django.views.generic import ListView

from smart_library.categories.models import Category
from smart_library.common.pagination_mixin import PaginationMixin
from smart_library.common.queryset_mixin import OrderedQuerysetMixin


class CategoriesView(OrderedQuerysetMixin, PaginationMixin, ListView):
    model = Category
    template_name = 'categories/categories.html'
    context_object_name = 'categories'
    paginate_by = 6

templates/categories/categories.html
{% extends 'base/base.html' %}
{% block title %} | Categories{% endblock %}
{% block page_content %}

<section class="common">
    <div class="common-list">
        {% for category in categories %}
        <div class="author-category-container">
            <div class="author-category-details">
                <p><strong>Category:</strong> {{ category.name }}</p>
                <h5>Books:</h5>
                <ul>
                    {% for book in category.book_set.all %}
                        <li>
                            <a href="{% url 'book details' pk=book.pk%}">
                                <img src="{{ book.book_image.url }}" alt="{{ book.book_title }} Image">
                            </a>
                        </li>

                    {% empty %}
                        <li>We are sorry, there are currently no books available in this category. Please check back later as we are constantly
                            updating our library with new titles. In the meantime, feel free to explore our other categories for exciting reads!"</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% endfor %}
    </div>

    {% include 'paginator.html' %}
</section>



{% endblock %}